/*
Collisions. Definition: A collision occurs when 
more than one value to be hashed by a particular
 hash function hash to the same slot in the table
  or data structure (hash table) being generated by the 
  hash function.

*/